<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup>
		<Title>Serilog.Sinks.ObservableCollection</Title>
		<Authors>Dillion Lowry</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Copyright (c) 2024 Dillion Lowry</Copyright>
		<Description>Custom Serilog sink designed to log messages to an ObservableCollection.</Description>
		<RepositoryUrl>https://github.com/DillionLowry/Serilog.Sinks.ObservableCollection</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/DillionLowry/Serilog.Sinks.ObservableCollection</PackageProjectUrl>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageTags>Serilog;Sink;ObservableCollection;Logging</PackageTags>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageVersion>2.0.0</PackageVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<DefineConstants>$(DefineConstants);FEATURE_ASYNCDISPOSABLE</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.4.0" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Assets\icon.png" />
		<Resource Include="Assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</Resource>
	</ItemGroup>

</Project>
